library(shiny)
library(shinydashboard)
library(vcfR)
library(DT)  # For interactive tables


ui <- fluidPage( 
    dashboardPage(
   # skin = "purple",
    dashboardHeader(title = span(img(src = "logo.png", height = 50), "RareInsight")),
    

    dashboardSidebar(
      sidebarMenu(
        menuItem("Home ", tabName = "home", icon = icon("home")),
        menuItem("About us", tabName = "Abt_us", icon = icon("users")),
        menuItem("Services", tabName = "service", icon = icon("bar-chart"),
                 menuSubItem("Input User Information", tabName = "input_user_info", icon = icon("user-circle")),
                 menuSubItem("Search Panel",tabName = "Search", icon = icon("glyphicon glyphicon-stats" )),
                 menuSubItem("Vcf Panel",tabName = "vcfpanel",icon = icon("file")),
                 menuSubItem("Diagnostic report", tabName = "diagnostic_report", icon = icon("line-chart"))
        ),
      menuItem("Acknowledgement", tabName = "acknow", icon = icon("handshake"))
      )
    ),

    dashboardBody(
      tags$head(tags$style(HTML('
                                /* logo */
                                .skin-blue .main-header .logo {
                                background-color: #030637;
                                }
                                
                                /* navbar (rest of the header) */
                                .skin-blue .main-header .navbar {
                                background-color: #030637;
                                }
                                
                                /* logo when hovered */
                                .skin-blue .main-header .logo:hover {
                                background-color: #030637;
                                }
                                
                                
                                
                                /* main sidebar */
                                .skin-blue .main-sidebar {
                                background-color: #3C0753;
                                }
                                
                                /* active selected tab in the sidebarmenu */
                                .skin-blue .main-sidebar .sidebar .sidebar-menu .active a{
                                background-color: #9f16db;
                                }
                                
                                /* other links in the sidebarmenu */
                                .skin-blue .main-sidebar .sidebar .sidebar-menu a{
                                background-color: ;
                                color: #FFFFFF
                                }
                                
                                /* other links in the sidebarmenu when hovered */
                                .skin-blue .main-sidebar .sidebar .sidebar-menu a:hover{
                                background-color: #030637;
                                }
                                /* toggle button when hovered  */
                                .skin-blue .main-header .navbar .sidebar-toggle:hover{
                                background-color: #3C0753;
                                }

                                /* body */
                                .content-wrapper, .right-side {
                                background-color: #FFFFFF	;
                                }
                                
                                '))),
        tabItems(
        tabItem(
          tabName = "home",
          fluidRow(
            box(title = "BLURB",
                status = "warning",
                solidHeader = TRUE,
                collapsible = TRUE,
                width = 6,
                p("RareInsight is a project aimed at tackling the challenges posed by rare diseases through collaborative efforts in research. Developed as an open-source, interactive dashboard tailored for both clinicians and patients, RareInsight focuses on transforming the interpretation of genetic variant data.The project's core objective is to simplify the complex process of diagnosing rare diseases and improving therapeutic outcomes. RareInsight processes genetic variant data into customizable, interactive reports, ideally generated by nf-core’s raredisease pipeline. These reports are derived from whole genome or whole exome sequencing data and offer advanced filtering options, statistical analysis capabilities, and diverse export formats.Developed using Shiny and tested with data from respected sources such as the Undiagnosed Disease Program and NHGRI GREGOR Consortium datasets found in dbGaP, RareInsight ensures accuracy and reliability. RareInsight aids informed decision-making for clinicians and patients alike and fosters collaboration among researchers and clinicians, facilitating seamless sharing and collaboration on reports. By promoting knowledge exchange, RareInsight aims to enrich the collective understanding of rare diseases and enhance healthcare outcomes in an open-source format.In summary, RareInsight is poised to revolutionize rare disease diagnosis and research by leveraging collaboration and innovation, ultimately reshaping the landscape of healthcare."
                )),
            box(title = "Aim",
                status = "danger",
                solidHeader = TRUE,
                collapsible = TRUE,
                width = 6,
                h4("  By promoting knowledge exchange, RareInsight aims to : "),
                p("1- Simplify the complex process of diagnosing rare diseases and improving therapeutic outcomes. "),
                p("2- Processes genetic variant data into customizable, interactive reports."),
                p("3- Ensures accuracy and reliability.  "),
                p("4- Facilitating seamless sharing and collaboration on reports.  "),
                p("5- Enrich the collective understanding of rare diseases  "),
                p("6- Enhance healthcare outcomes in an open-source format. "),
                p("7- Revolutionize rare disease diagnosis and research by leveraging collaboration and innovation, ultimately reshaping the landscape of healthcare. ")
            )
          )
        ),

        tabItem(
          tabName = "Abt_us",
          h1("Intoduction for members "),
          h3("it should be the last tab")
        ),

        tabItem(
          tabName = "service",
          h1("User Data Inputs")
        ),
        tabItem(
          tabName = "input_user_info",
          h1(" User Data Inputs"),
          fluidRow(
            column(6, textInput(inputId = "name", label = "Name")),
            column(6, textInput(inputId = "surname", label = "Surname")),
            column(6, textInput(inputId = "ethnicity", label = "Ethnicity")),
            column(6, dateInput(inputId = "dob", label = "Date of Birth")),
            column(12, textInput(inputId = "clinical_diagnosis", label = "Clinical Diagnosis (OMIM")),
            column(12, textInput(inputId = "phenotype", label = "Phenotype (HPO Terms)")),
            column(12, selectInput(inputId = "rest_performed", label = "Test Performed", choices = c("WES", "WGS", "Gene Panel"))),
            downloadButton(outputId = "download_button", label = "Download User Info")
          )
        ),

        tabItem(
          tabName = "Search",
          h1("Search Panel"),
             fluidRow(
               wellPanel(
               selectInput("search_type", "Search Type:",
                           choices = c("Gene", "Variant", "Disorder"),
                            selected = "Gene"),
               textInput("search_input", "Enter Search Term:", ""),
               actionButton("search_button", "Search"),
               DTOutput("search_results")
               ),
               box(
                 title = "Brief discription"
               )
            )
          
        ),
        tabItem(
          tabName = "vcfpanel",
           h1("VCF Panel"),
           # Added file input
           fileInput("input_file", "Upload VCF File", accept = c(".vcf.gz")),
           tabsetPanel(
             tabPanel("Results",
                      fluidRow(
                        wellPanel(
                          title = "Variant Information",
                          solidHeader = TRUE,
                          status = "primary",
                          div(style = "overflow-x: scroll; width: 100%;",
                              tableOutput("variant_table")
                          )
                        )
                      )
             ),
             tabPanel(
               "Graphs",
               fluidRow(
                 
               )
             )
           )
          ),
        
        tabItem(
          tabName = "diagnostic_report",
          tabPanel("Clinician and Researcher Support", "Clinician and researcher support information will be displayed here"),
          tabPanel("Patient Support", "Patient support information will be displayed here"),
          tabPanel("ACMG Classification", "ACMG classification information will be displayed here"),
          tabPanel("Disorder", "Clinical information will be displayed here")
        ),

        tabItem(
          tabName = "acknow",
          h1("Thank you to the following people and organizations:"),
          h4("African Society for Bioinformatics and Computational Biology",
             img(src = "asbcb-logo.png", height = 50, width = 50))
         )
       )
    )
  )
)
variant_summary <- read.delim("variant_summary.txt", stringsAsFactors = FALSE)

server <- function(input, output, session) {
  ###########################  ########################### 
  ## user input part : 
   user_info_text <- reactive({
    paste(
      "Name: ", input$name,"\n",
      "Surname: ", input$surname,"\n",
      "Ethnicity: ", input$ethnicity,"\n",
      "Date of Birth: ", input$dob,"\n",
      "Clinical Diagnosis (OMIM): ", input$clinical_diagnosis,"\n",
      "Phenotype (HPO Terms): ", input$phenotype,"\n",
      "Test Performed: ", input$rest_performed,"\n"
    )
  })
  
  # Function to generate downloadable user info content
  output$download_button <- downloadHandler(
    filename = function() {
      paste("user_info_", Sys.Date(), ".txt", sep = "")
    },
    content = function(file) {
      writeLines(user_info_text(), file)
    }
  )
  ###########################  ###########################   
  ### Search Panel part
  
  observeEvent(input$search_button, {
    search_term <- input$search_input
    search_type <- input$search_type
    # Define the column to search based on search type
    search_column <- switch(
      search_type,
      "Gene" = "GeneSymbol",
      "Variant" = "Name",
      "Disorder" = "PhenotypeList"
    )
    # Filter data based on search term and column
    filtered_data <- variant_summary[grep(search_term, variant_summary[[search_column]], ignore.case = TRUE), ]
    output$search_results <- renderDT({
      if(nrow(filtered_data) == 0) {
        # Display a message if no results are found
        HTML("<p>No matching results found.</p>")
      } else {
        datatable(filtered_data, options = list(scrollX = TRUE))
      }
    })
  })
  ###########################  ########################### 
  ## VCF upload file part
  vcf_data <- reactive({
    req(input$input_file)
    vcf_file <- input$input_file$datapath
    vcf_data <- read.vcfR(vcf_file)
    return(vcf_data)
  })
  
  output$variant_table <- renderTable({
    req(vcf_data())
  
    # Extract variant information and filter PASS variants
    variant_info <- as.data.frame(vcf_data()@fix)
    ############ variant_info <- variant_info[variant_info$FILTER == "PASS", ]

    # Remove ID and QUAL columns
    ############ variant_info <- subset(variant_info, select = -c(ID, QUAL))
    
    # Remobe ID is not Abvailable "NA"
    if (any(is.na(variant_info$ID))) {
      variant_info <- subset(variant_info, select = -c(ID))
    }
    
    # Split INFO column into separate columns
    info_split <- strsplit(as.character(variant_info$INFO), ";")
    max_splits <- max(lengths(info_split))
    
    # Create dataframe to store split columns
    info_df <- data.frame(matrix(NA, ncol = max_splits, nrow = nrow(variant_info)))
    
    # Extract column names and values from INFO column
    info_names_values <- lapply(info_split, function(x) {
      splits <- strsplit(x, "=")
      names <- sapply(splits, `[`, 1)
      values <- sapply(splits, `[`, 2)
      return(list(names = names, values = values))
    })
    
    # Fill in split columns with appropriate column names
    for (i in 1:max_splits) {
      column_values <- sapply(info_names_values, function(info) ifelse(length(info$values) >= i, info$values[i], NA))
      col_names <- unique(unlist(sapply(info_names_values, function(info) ifelse(length(info$names) >= i, info$names[i], NA))))
      colnames(info_df)[i] <- col_names
      info_df[, i] <- column_values
    }
    
    # Combine split INFO columns with original dataframe
    variant_info <- cbind(variant_info, info_df)
    
    # Remove original INFO column
    variant_info <- subset(variant_info, select = -INFO)
    
    return(variant_info)
  })
}


shinyApp(ui, server)
